package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AnneeAcademique generated by hbm2java
 */
@Entity
@Table(name = "annee_academique", catalog = "gestion_reclamation")
public class AnneeAcademique implements java.io.Serializable {

	private int idAnneeAcademique;
	private String anneeDebut;
	private String anneeFin;
	private String libelleanneacademique;
	private Set<Attribution> attributions = new HashSet<Attribution>(0);
	private Set<Parcours> parcourses = new HashSet<Parcours>(0);

	public AnneeAcademique() {
	}

	public AnneeAcademique(int idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	public AnneeAcademique(int idAnneeAcademique, String anneeDebut, String anneeFin, String libelleanneacademique,
			Set<Attribution> attributions, Set<Parcours> parcourses) {
		this.idAnneeAcademique = idAnneeAcademique;
		this.anneeDebut = anneeDebut;
		this.anneeFin = anneeFin;
		this.libelleanneacademique = libelleanneacademique;
		this.attributions = attributions;
		this.parcourses = parcourses;
	}

	@Id

	@Column(name = "ID_ANNEE_ACADEMIQUE", unique = true, nullable = false)
	public int getIdAnneeAcademique() {
		return this.idAnneeAcademique;
	}

	public void setIdAnneeAcademique(int idAnneeAcademique) {
		this.idAnneeAcademique = idAnneeAcademique;
	}

	@Column(name = "ANNEE_DEBUT", length = 10)
	public String getAnneeDebut() {
		return this.anneeDebut;
	}

	public void setAnneeDebut(String anneeDebut) {
		this.anneeDebut = anneeDebut;
	}

	@Column(name = "ANNEE_FIN", length = 10)
	public String getAnneeFin() {
		return this.anneeFin;
	}

	public void setAnneeFin(String anneeFin) {
		this.anneeFin = anneeFin;
	}

	@Column(name = "LIBELLEANNEACADEMIQUE", length = 10)
	public String getLibelleanneacademique() {
		return this.libelleanneacademique;
	}

	public void setLibelleanneacademique(String libelleanneacademique) {
		this.libelleanneacademique = libelleanneacademique;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeAcademique")
	public Set<Attribution> getAttributions() {
		return this.attributions;
	}

	public void setAttributions(Set<Attribution> attributions) {
		this.attributions = attributions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeAcademique")
	public Set<Parcours> getParcourses() {
		return this.parcourses;
	}

	public void setParcourses(Set<Parcours> parcourses) {
		this.parcourses = parcourses;
	}

}
