package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecue generated by hbm2java
 */
@Entity
@Table(name = "ecue", catalog = "gestion_reclamation")
public class Ecue implements java.io.Serializable {

	private String codeEcue;
	private Ue ue;
	private String intituleEcue;
	private Integer creditEcue;
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);
	private Set<Attribution> attributions = new HashSet<Attribution>(0);

	public Ecue() {
	}

	public Ecue(String codeEcue, Ue ue) {
		this.codeEcue = codeEcue;
		this.ue = ue;
	}

	public Ecue(String codeEcue, Ue ue, String intituleEcue, Integer creditEcue, Set<Evaluation> evaluations,
			Set<Attribution> attributions) {
		this.codeEcue = codeEcue;
		this.ue = ue;
		this.intituleEcue = intituleEcue;
		this.creditEcue = creditEcue;
		this.evaluations = evaluations;
		this.attributions = attributions;
	}

	@Id

	@Column(name = "CODE_ECUE", unique = true, nullable = false, length = 10)
	public String getCodeEcue() {
		return this.codeEcue;
	}

	public void setCodeEcue(String codeEcue) {
		this.codeEcue = codeEcue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_UE", nullable = false)
	public Ue getUe() {
		return this.ue;
	}

	public void setUe(Ue ue) {
		this.ue = ue;
	}

	@Column(name = "INTITULE_ECUE", length = 50)
	public String getIntituleEcue() {
		return this.intituleEcue;
	}

	public void setIntituleEcue(String intituleEcue) {
		this.intituleEcue = intituleEcue;
	}

	@Column(name = "CREDIT_ECUE")
	public Integer getCreditEcue() {
		return this.creditEcue;
	}

	public void setCreditEcue(Integer creditEcue) {
		this.creditEcue = creditEcue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecue")
	public Set<Evaluation> getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecue")
	public Set<Attribution> getAttributions() {
		return this.attributions;
	}

	public void setAttributions(Set<Attribution> attributions) {
		this.attributions = attributions;
	}

}
