package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "gestion_reclamation")
public class Enseignant implements java.io.Serializable {

	private int idActeur;
	private Acteur acteur;
	private Integer idGenre;
	private String matriculeActeur;
	private String nomActeur;
	private String prenomsActeur;
	private Long telephoneActeur;
	private Set<Attribution> attributions = new HashSet<Attribution>(0);

	public Enseignant() {
	}

	public Enseignant(Acteur acteur) {
		this.acteur = acteur;
	}

	public Enseignant(Acteur acteur, Integer idGenre, String matriculeActeur, String nomActeur, String prenomsActeur,
			Long telephoneActeur, Set<Attribution> attributions) {
		this.acteur = acteur;
		this.idGenre = idGenre;
		this.matriculeActeur = matriculeActeur;
		this.nomActeur = nomActeur;
		this.prenomsActeur = prenomsActeur;
		this.telephoneActeur = telephoneActeur;
		this.attributions = attributions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "acteur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_ACTEUR", unique = true, nullable = false)
	public int getIdActeur() {
		return this.idActeur;
	}

	public void setIdActeur(int idActeur) {
		this.idActeur = idActeur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	@Column(name = "ID_GENRE")
	public Integer getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(Integer idGenre) {
		this.idGenre = idGenre;
	}

	@Column(name = "MATRICULE_ACTEUR", length = 10)
	public String getMatriculeActeur() {
		return this.matriculeActeur;
	}

	public void setMatriculeActeur(String matriculeActeur) {
		this.matriculeActeur = matriculeActeur;
	}

	@Column(name = "NOM_ACTEUR", length = 50)
	public String getNomActeur() {
		return this.nomActeur;
	}

	public void setNomActeur(String nomActeur) {
		this.nomActeur = nomActeur;
	}

	@Column(name = "PRENOMS_ACTEUR", length = 100)
	public String getPrenomsActeur() {
		return this.prenomsActeur;
	}

	public void setPrenomsActeur(String prenomsActeur) {
		this.prenomsActeur = prenomsActeur;
	}

	@Column(name = "TELEPHONE_ACTEUR")
	public Long getTelephoneActeur() {
		return this.telephoneActeur;
	}

	public void setTelephoneActeur(Long telephoneActeur) {
		this.telephoneActeur = telephoneActeur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enseignant")
	public Set<Attribution> getAttributions() {
		return this.attributions;
	}

	public void setAttributions(Set<Attribution> attributions) {
		this.attributions = attributions;
	}

}
