package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtatReclamation generated by hbm2java
 */
@Entity
@Table(name = "etat_reclamation", catalog = "gestion_reclamation")
public class EtatReclamation implements java.io.Serializable {

	private int idEtatreclamation;
	private String libelleetatreclamation;
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public EtatReclamation() {
	}

	public EtatReclamation(int idEtatreclamation) {
		this.idEtatreclamation = idEtatreclamation;
	}

	public EtatReclamation(int idEtatreclamation, String libelleetatreclamation, Set<Reclamation> reclamations) {
		this.idEtatreclamation = idEtatreclamation;
		this.libelleetatreclamation = libelleetatreclamation;
		this.reclamations = reclamations;
	}

	@Id

	@Column(name = "ID_ETATRECLAMATION", unique = true, nullable = false)
	public int getIdEtatreclamation() {
		return this.idEtatreclamation;
	}

	public void setIdEtatreclamation(int idEtatreclamation) {
		this.idEtatreclamation = idEtatreclamation;
	}

	@Column(name = "LIBELLEETATRECLAMATION", length = 100)
	public String getLibelleetatreclamation() {
		return this.libelleetatreclamation;
	}

	public void setLibelleetatreclamation(String libelleetatreclamation) {
		this.libelleetatreclamation = libelleetatreclamation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatReclamation")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
