package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "gestion_reclamation")
public class Etudiant implements java.io.Serializable {

	private int idActeur;
	private Acteur acteur;
	private Filiere filiere;
	private Integer idGenre;
	private String matriculeActeur;
	private String nomActeur;
	private String prenomsActeur;
	private Long telephoneActeur;
	private Date dateDeNaissance;
	private Set<Parcours> parcourses = new HashSet<Parcours>(0);
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public Etudiant() {
	}

	public Etudiant(Acteur acteur, Filiere filiere) {
		this.acteur = acteur;
		this.filiere = filiere;
	}

	public Etudiant(Acteur acteur, Filiere filiere, Integer idGenre, String matriculeActeur, String nomActeur,
			String prenomsActeur, Long telephoneActeur, Date dateDeNaissance, Set<Parcours> parcourses,
			Set<Reclamation> reclamations) {
		this.acteur = acteur;
		this.filiere = filiere;
		this.idGenre = idGenre;
		this.matriculeActeur = matriculeActeur;
		this.nomActeur = nomActeur;
		this.prenomsActeur = prenomsActeur;
		this.telephoneActeur = telephoneActeur;
		this.dateDeNaissance = dateDeNaissance;
		this.parcourses = parcourses;
		this.reclamations = reclamations;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "acteur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_ACTEUR", unique = true, nullable = false)
	public int getIdActeur() {
		return this.idActeur;
	}

	public void setIdActeur(int idActeur) {
		this.idActeur = idActeur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FILIERE", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "ID_GENRE")
	public Integer getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(Integer idGenre) {
		this.idGenre = idGenre;
	}

	@Column(name = "MATRICULE_ACTEUR", length = 10)
	public String getMatriculeActeur() {
		return this.matriculeActeur;
	}

	public void setMatriculeActeur(String matriculeActeur) {
		this.matriculeActeur = matriculeActeur;
	}

	@Column(name = "NOM_ACTEUR", length = 50)
	public String getNomActeur() {
		return this.nomActeur;
	}

	public void setNomActeur(String nomActeur) {
		this.nomActeur = nomActeur;
	}

	@Column(name = "PRENOMS_ACTEUR", length = 100)
	public String getPrenomsActeur() {
		return this.prenomsActeur;
	}

	public void setPrenomsActeur(String prenomsActeur) {
		this.prenomsActeur = prenomsActeur;
	}

	@Column(name = "TELEPHONE_ACTEUR")
	public Long getTelephoneActeur() {
		return this.telephoneActeur;
	}

	public void setTelephoneActeur(Long telephoneActeur) {
		this.telephoneActeur = telephoneActeur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DE_NAISSANCE", length = 10)
	public Date getDateDeNaissance() {
		return this.dateDeNaissance;
	}

	public void setDateDeNaissance(Date dateDeNaissance) {
		this.dateDeNaissance = dateDeNaissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Parcours> getParcourses() {
		return this.parcourses;
	}

	public void setParcourses(Set<Parcours> parcourses) {
		this.parcourses = parcourses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
