package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "gestion_reclamation")
public class Genre implements java.io.Serializable {

	private int idGenre;
	private String libellegenre;
	private Set<Acteur> acteurs = new HashSet<Acteur>(0);

	public Genre() {
	}

	public Genre(int idGenre) {
		this.idGenre = idGenre;
	}

	public Genre(int idGenre, String libellegenre, Set<Acteur> acteurs) {
		this.idGenre = idGenre;
		this.libellegenre = libellegenre;
		this.acteurs = acteurs;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_GENRE", unique = true, nullable = false)
	public int getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(int idGenre) {
		this.idGenre = idGenre;
	}

	@Column(name = "LIBELLEGENRE", length = 10)
	public String getLibellegenre() {
		return this.libellegenre;
	}

	public void setLibellegenre(String libellegenre) {
		this.libellegenre = libellegenre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Acteur> getActeurs() {
		return this.acteurs;
	}

	public void setActeurs(Set<Acteur> acteurs) {
		this.acteurs = acteurs;
	}

}
