package com.upb.model;
// Generated 14 sept. 2022 � 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MotifReclamation generated by hbm2java
 */
@Entity
@Table(name = "motif_reclamation", catalog = "gestion_reclamation")
public class MotifReclamation implements java.io.Serializable {

	private int idMotifreclamation;
	private String libellemotifreclamation;
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public MotifReclamation() {
	}

	public MotifReclamation(int idMotifreclamation) {
		this.idMotifreclamation = idMotifreclamation;
	}

	public MotifReclamation(int idMotifreclamation, String libellemotifreclamation, Set<Reclamation> reclamations) {
		this.idMotifreclamation = idMotifreclamation;
		this.libellemotifreclamation = libellemotifreclamation;
		this.reclamations = reclamations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_MOTIFRECLAMATION", unique = true, nullable = false)
	public int getIdMotifreclamation() {
		return this.idMotifreclamation;
	}

	public void setIdMotifreclamation(int idMotifreclamation) {
		this.idMotifreclamation = idMotifreclamation;
	}

	@Column(name = "LIBELLEMOTIFRECLAMATION", length = 100)
	public String getLibellemotifreclamation() {
		return this.libellemotifreclamation;
	}

	public void setLibellemotifreclamation(String libellemotifreclamation) {
		this.libellemotifreclamation = libellemotifreclamation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motifReclamation")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
