package com.upb.model;
// Generated 14 sept. 2022 � 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", catalog = "gestion_reclamation")
public class Niveau implements java.io.Serializable {

	private int idNiveau;
	private String nomNiveau;
	private Set<Parcours> parcourses = new HashSet<Parcours>(0);

	public Niveau() {
	}

	public Niveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	public Niveau(int idNiveau, String nomNiveau, Set<Parcours> parcourses) {
		this.idNiveau = idNiveau;
		this.nomNiveau = nomNiveau;
		this.parcourses = parcourses;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_NIVEAU", unique = true, nullable = false)
	public int getIdNiveau() {
		return this.idNiveau;
	}

	public void setIdNiveau(int idNiveau) {
		this.idNiveau = idNiveau;
	}

	@Column(name = "NOM_NIVEAU", length = 10)
	public String getNomNiveau() {
		return this.nomNiveau;
	}

	public void setNomNiveau(String nomNiveau) {
		this.nomNiveau = nomNiveau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveau")
	public Set<Parcours> getParcourses() {
		return this.parcourses;
	}

	public void setParcourses(Set<Parcours> parcourses) {
		this.parcourses = parcourses;
	}

}
