package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Parcours generated by hbm2java
 */
@Entity
@Table(name = "parcours", catalog = "gestion_reclamation")
public class Parcours implements java.io.Serializable {

	private int idParcours;
	private AnneeAcademique anneeAcademique;
	private Etudiant etudiant;
	private Niveau niveau;

	public Parcours() {
	}

	public Parcours(int idParcours, AnneeAcademique anneeAcademique, Etudiant etudiant, Niveau niveau) {
		this.idParcours = idParcours;
		this.anneeAcademique = anneeAcademique;
		this.etudiant = etudiant;
		this.niveau = niveau;
	}

	@Id

	@Column(name = "ID_PARCOURS", unique = true, nullable = false)
	public int getIdParcours() {
		return this.idParcours;
	}

	public void setIdParcours(int idParcours) {
		this.idParcours = idParcours;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANNEE_ACADEMIQUE", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTEUR", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NIVEAU", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

}
