package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name = "reclamation", catalog = "gestion_reclamation")
public class Reclamation implements java.io.Serializable {

	private int idReclamation;
	private EtatReclamation etatReclamation;
	private Etudiant etudiant;
	private Evaluation evaluation;
	private MotifReclamation motifReclamation;
	private RetourReclamation retourReclamation;
	private Date dateReclamation;
	private Set<RetourReclamation> retourReclamations = new HashSet<RetourReclamation>(0);

	public Reclamation() {
	}

	public Reclamation(int idReclamation, EtatReclamation etatReclamation, Etudiant etudiant, Evaluation evaluation,
			MotifReclamation motifReclamation) {
		this.idReclamation = idReclamation;
		this.etatReclamation = etatReclamation;
		this.etudiant = etudiant;
		this.evaluation = evaluation;
		this.motifReclamation = motifReclamation;
	}

	public Reclamation(int idReclamation, EtatReclamation etatReclamation, Etudiant etudiant, Evaluation evaluation,
			MotifReclamation motifReclamation, RetourReclamation retourReclamation, Date dateReclamation,
			Set<RetourReclamation> retourReclamations) {
		this.idReclamation = idReclamation;
		this.etatReclamation = etatReclamation;
		this.etudiant = etudiant;
		this.evaluation = evaluation;
		this.motifReclamation = motifReclamation;
		this.retourReclamation = retourReclamation;
		this.dateReclamation = dateReclamation;
		this.retourReclamations = retourReclamations;
	}

	@Id

	@Column(name = "ID_RECLAMATION", unique = true, nullable = false)
	public int getIdReclamation() {
		return this.idReclamation;
	}

	public void setIdReclamation(int idReclamation) {
		this.idReclamation = idReclamation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ETATRECLAMATION", nullable = false)
	public EtatReclamation getEtatReclamation() {
		return this.etatReclamation;
	}

	public void setEtatReclamation(EtatReclamation etatReclamation) {
		this.etatReclamation = etatReclamation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTEUR", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EVALUATION", nullable = false)
	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MOTIFRECLAMATION", nullable = false)
	public MotifReclamation getMotifReclamation() {
		return this.motifReclamation;
	}

	public void setMotifReclamation(MotifReclamation motifReclamation) {
		this.motifReclamation = motifReclamation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_RETOURRECLAMATION")
	public RetourReclamation getRetourReclamation() {
		return this.retourReclamation;
	}

	public void setRetourReclamation(RetourReclamation retourReclamation) {
		this.retourReclamation = retourReclamation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RECLAMATION", length = 19)
	public Date getDateReclamation() {
		return this.dateReclamation;
	}

	public void setDateReclamation(Date dateReclamation) {
		this.dateReclamation = dateReclamation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reclamation")
	public Set<RetourReclamation> getRetourReclamations() {
		return this.retourReclamations;
	}

	public void setRetourReclamations(Set<RetourReclamation> retourReclamations) {
		this.retourReclamations = retourReclamations;
	}

}
