package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RetourReclamation generated by hbm2java
 */
@Entity
@Table(name = "retour_reclamation", catalog = "gestion_reclamation")
public class RetourReclamation implements java.io.Serializable {

	private String codeRetourreclamation;
	private Reclamation reclamation;
	private String libelleretourreclamation;
	private Date dateretourreclamation;
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public RetourReclamation() {
	}

	public RetourReclamation(String codeRetourreclamation, Reclamation reclamation) {
		this.codeRetourreclamation = codeRetourreclamation;
		this.reclamation = reclamation;
	}

	public RetourReclamation(String codeRetourreclamation, Reclamation reclamation, String libelleretourreclamation,
			Date dateretourreclamation, Set<Reclamation> reclamations) {
		this.codeRetourreclamation = codeRetourreclamation;
		this.reclamation = reclamation;
		this.libelleretourreclamation = libelleretourreclamation;
		this.dateretourreclamation = dateretourreclamation;
		this.reclamations = reclamations;
	}

	@Id

	@Column(name = "CODE_RETOURRECLAMATION", unique = true, nullable = false, length = 10)
	public String getCodeRetourreclamation() {
		return this.codeRetourreclamation;
	}

	public void setCodeRetourreclamation(String codeRetourreclamation) {
		this.codeRetourreclamation = codeRetourreclamation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RECLAMATION", nullable = false)
	public Reclamation getReclamation() {
		return this.reclamation;
	}

	public void setReclamation(Reclamation reclamation) {
		this.reclamation = reclamation;
	}

	@Column(name = "LIBELLERETOURRECLAMATION", length = 100)
	public String getLibelleretourreclamation() {
		return this.libelleretourreclamation;
	}

	public void setLibelleretourreclamation(String libelleretourreclamation) {
		this.libelleretourreclamation = libelleretourreclamation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATERETOURRECLAMATION", length = 10)
	public Date getDateretourreclamation() {
		return this.dateretourreclamation;
	}

	public void setDateretourreclamation(Date dateretourreclamation) {
		this.dateretourreclamation = dateretourreclamation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retourReclamation")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
