package com.upb.model;
// Generated 14 sept. 2022 � 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "gestion_reclamation")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private String intituleSemestre;
	private Set<Ue> ues = new HashSet<Ue>(0);

	public Semestre() {
	}

	public Semestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	public Semestre(int idSemestre, String intituleSemestre, Set<Ue> ues) {
		this.idSemestre = idSemestre;
		this.intituleSemestre = intituleSemestre;
		this.ues = ues;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_SEMESTRE", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "INTITULE_SEMESTRE", length = 30)
	public String getIntituleSemestre() {
		return this.intituleSemestre;
	}

	public void setIntituleSemestre(String intituleSemestre) {
		this.intituleSemestre = intituleSemestre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestre")
	public Set<Ue> getUes() {
		return this.ues;
	}

	public void setUes(Set<Ue> ues) {
		this.ues = ues;
	}

}
