package com.upb.model;
// Generated 14 sept. 2022 � 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TypeEvaluation generated by hbm2java
 */
@Entity
@Table(name = "type_evaluation", catalog = "gestion_reclamation")
public class TypeEvaluation implements java.io.Serializable {

	private int idTypeEvaluation;
	private String devoir;
	private String sessionExamen;
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);

	public TypeEvaluation() {
	}

	public TypeEvaluation(int idTypeEvaluation) {
		this.idTypeEvaluation = idTypeEvaluation;
	}

	public TypeEvaluation(int idTypeEvaluation, String devoir, String sessionExamen, Set<Evaluation> evaluations) {
		this.idTypeEvaluation = idTypeEvaluation;
		this.devoir = devoir;
		this.sessionExamen = sessionExamen;
		this.evaluations = evaluations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "ID_TYPE_EVALUATION", unique = true, nullable = false)
	public int getIdTypeEvaluation() {
		return this.idTypeEvaluation;
	}

	public void setIdTypeEvaluation(int idTypeEvaluation) {
		this.idTypeEvaluation = idTypeEvaluation;
	}

	@Column(name = "DEVOIR", length = 10)
	public String getDevoir() {
		return this.devoir;
	}

	public void setDevoir(String devoir) {
		this.devoir = devoir;
	}

	@Column(name = "SESSION_EXAMEN", length = 10)
	public String getSessionExamen() {
		return this.sessionExamen;
	}

	public void setSessionExamen(String sessionExamen) {
		this.sessionExamen = sessionExamen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEvaluation")
	public Set<Evaluation> getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}

}
