package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ue generated by hbm2java
 */
@Entity
@Table(name = "ue", catalog = "gestion_reclamation")
public class Ue implements java.io.Serializable {

	private String codeUe;
	private Semestre semestre;
	private String intituleUe;
	private Integer creditUe;
	private Set<Ecue> ecues = new HashSet<Ecue>(0);

	public Ue() {
	}

	public Ue(String codeUe, Semestre semestre) {
		this.codeUe = codeUe;
		this.semestre = semestre;
	}

	public Ue(String codeUe, Semestre semestre, String intituleUe, Integer creditUe, Set<Ecue> ecues) {
		this.codeUe = codeUe;
		this.semestre = semestre;
		this.intituleUe = intituleUe;
		this.creditUe = creditUe;
		this.ecues = ecues;
	}

	@Id

	@Column(name = "CODE_UE", unique = true, nullable = false, length = 10)
	public String getCodeUe() {
		return this.codeUe;
	}

	public void setCodeUe(String codeUe) {
		this.codeUe = codeUe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SEMESTRE", nullable = false)
	public Semestre getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}

	@Column(name = "INTITULE_UE", length = 50)
	public String getIntituleUe() {
		return this.intituleUe;
	}

	public void setIntituleUe(String intituleUe) {
		this.intituleUe = intituleUe;
	}

	@Column(name = "CREDIT_UE")
	public Integer getCreditUe() {
		return this.creditUe;
	}

	public void setCreditUe(Integer creditUe) {
		this.creditUe = creditUe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ue")
	public Set<Ecue> getEcues() {
		return this.ecues;
	}

	public void setEcues(Set<Ecue> ecues) {
		this.ecues = ecues;
	}

}
