package com.upb.model;
// Generated 14 sept. 2022 à 17:02:16 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthentification generated by hbm2java
 */
@Entity
@Table(name = "user_authentification", catalog = "gestion_reclamation")
public class UserAuthentification implements java.io.Serializable {

	private int iduser;
	private Acteur acteur;
	private UserAuthorisation userAuthorisation;
	private String login;
	private String password;

	public UserAuthentification() {
	}

	public UserAuthentification(int iduser, Acteur acteur, UserAuthorisation userAuthorisation) {
		this.iduser = iduser;
		this.acteur = acteur;
		this.userAuthorisation = userAuthorisation;
	}

	public UserAuthentification(int iduser, Acteur acteur, UserAuthorisation userAuthorisation, String login,
			String password) {
		this.iduser = iduser;
		this.acteur = acteur;
		this.userAuthorisation = userAuthorisation;
		this.login = login;
		this.password = password;
	}

	@Id

	@Column(name = "IDUSER", unique = true, nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTEUR", nullable = false)
	public Acteur getActeur() {
		return this.acteur;
	}

	public void setActeur(Acteur acteur) {
		this.acteur = acteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER_AUTHORISATION", nullable = false)
	public UserAuthorisation getUserAuthorisation() {
		return this.userAuthorisation;
	}

	public void setUserAuthorisation(UserAuthorisation userAuthorisation) {
		this.userAuthorisation = userAuthorisation;
	}

	@Column(name = "LOGIN", length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
